export const categories = [
    {
        name: "Design",
        color: "#FFB347",
        subcategories: [
            "Graphics & Design",
            "UI/UX Design",
            "Logo Design",
            "Print Design",
            "Web Design",
            "Illustration",
            "Branding",
            "Photography",
        ],
    },
    {
        name: "Development",
        color: "#7EC8E3",
        subcategories: [
            "Web Development",
            "Mobile Apps",
            "Desktop Apps",
            "Game Development",
            "WordPress",
            "Shopify",
            "APIs & Integrations",
            "DevOps",
        ],
    },
    {
        name: "Business",
        color: "#FF6B6B",
        subcategories: [
            "Marketing",
            "Sales",
            "Finance",
            "Project Management",
            "Productivity",
            "Analytics",
            "Customer Service",
            "HR & Recruiting",
        ],
    },
    {
        name: "Education",
        color: "#FFB347",
        subcategories: [
            "Online Courses",
            "Tutorials",
            "E-books",
            "Templates",
            "Study Guides",
            "Certification Prep",
            "Language Learning",
            "Skill Development",
        ],
    },
    {
        name: "Creative",
        color: "#96E6B3",
        subcategories: [
            "Music & Audio",
            "Video & Animation",
            "Writing & Content",
            "Art & Crafts",
            "Photography",
            "Digital Art",
            "Stock Media",
            "Creative Tools",
        ],
    },
    {
        name: "Lifestyle",
        color: "#FFE066",
        subcategories: [
            "Health & Fitness",
            "Food & Cooking",
            "Travel",
            "Fashion",
            "Home & Garden",
            "Personal Development",
            "Hobbies",
            "Relationships",
        ],
    },
]